server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  enabled: false

extraScrapeConfigs: |
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi-service.default.svc.cluster.local:8000']
