name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image with Git SHA tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t dhanush789245/fastapi-mistralai-app:$IMAGE_TAG -t dhanush789245/fastapi-mistralai-app:latest .
        docker push dhanush789245/fastapi-mistralai-app:$IMAGE_TAG
        docker push dhanush789245/fastapi-mistralai-app:latest
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Clone GitOps repo and update image tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/Dhanush0369/gitops-repo.git
        cd gitops-repo/k8s
        sed -i "s|image: .*|image: dhanush789245/fastapi-mistralai-app:${{ env.IMAGE_TAG }}|g" deployment.yaml

        git add deployment.yaml
        git commit -m "Update image to tag ${{ env.IMAGE_TAG }}"
        git push
